spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379


  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false

  # 이하 devtools 옵션은 배포시 삭제 필요
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

server:
  error:
    include-message: always