spring:
  datasource:
    username: root
    password: wjtmd1
    url: jdbc:mysql://localhost:3306/party?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false

server:
  error:
    include-message: always

cloud:
  aws:
    s3:
      bucket: letsparty
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAT4USRYSPRW6PNXQR
      secretKey: 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