spring:
  datasource:
    username: ${{ secrets.DB_USER }}
    password: ${{ secrets.DB_PASSWORD }}
    url: ${{ secrets.DB_URL }}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false

server:
  error:
    include-message: always

cloud:
  aws:
    s3:
      bucket: letsparty
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${{ secrets.S3_ACCESS_KEY_ID }}
      secretKey: ${{ secrets.S3_SECRET_KEY_ID }}
