cloud:
  aws:
    s3:
      bucket: letsparty
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${{ secrets.S3_ACCESS_KEY_ID }}
      secretKey: ${{ secrets.S3_SECRET_KEY_ID }}
