spring:
  datasource:
    username: jwadmin
    password: abc!123#45678!#
    url: jdbc:mysql://party.czqpruw2g0gl.ap-northeast-2.rds.amazonaws.com:3306/party?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    host: party-redis.ojt0iz.ng.0001.apn2.cache.amazonaws.com
    port: 6379

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false

server:
  error:
    include-message: always

cloud:
  aws:
    s3:
      bucket: letsparty
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAT4USRYSPRW6PNXQR
      secretKey: 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
