spring:
  datasource:
    username: jwadmin
    password: abc!12345#678!
    url: jdbc:mysql://party.czqpruw2g0gl.ap-northeast-2.rds.amazonaws.com:3306/party?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: application-aws.yml

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: party-redis.ojt0iz.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    #redis의 host 값은 로컬기동시 :localhost / 원격 기동시 AWS redis 접속주소 입력해야 합니다

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false

server:
  error:
    include-message: always

cloud:
  aws:
    s3:
      bucket: letsparty
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAT4USRYSP7WHED24W
      secretKey: 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